import React, { useState, useEffect, useMemo } from 'react';
import { getReferrals } from '../api/referrals';
import { Badge } from '../components/ui/Badge';
import { Input } from '../components/ui/Input';
import { Search, MapPin, Clock, Building2, ChevronRight, Stethoscope, AlertCircle, FileText, X, Printer, User, HeartPulse, Sparkles } from 'lucide-react';

const ReferralStatus = () => {
    const [referrals, setReferrals] = useState([]);
    const [isLoading, setIsLoading] = useState(true);
    const [searchTerm, setSearchTerm] = useState('');
    const [selectedReferral, setSelectedReferral] = useState(null);

    useEffect(() => {
        const fetchReferrals = async () => {
            try {
                await getReferrals(); // Ensure api fires for demo completeness
                const localData = JSON.parse(localStorage.getItem('referrals')) || [];
                if (localData.length > 0) {
                    setReferrals(localData);
                } else {
                    const data = await getReferrals();
                    setReferrals(data);
                }
            } catch (error) {
                console.error("Failed to load referrals", error);
            } finally {
                setIsLoading(false);
            }
        };

        fetchReferrals();
    }, []);

    // Helper functions for mock data enhancement
    const getUrgencySettings = (scoreStr) => {
        const score = parseInt(scoreStr, 10);
        if (isNaN(score)) return { color: 'bg-surface-100 text-surface-700 border-surface-200', label: 'Unknown', icon: AlertCircle };
        if (score >= 80) return { color: 'bg-red-50 text-red-700 border-red-200', label: 'Critical', icon: AlertCircle };
        if (score >= 60) return { color: 'bg-amber-50 text-amber-700 border-amber-200', label: 'Urgent', icon: Clock };
        return { color: 'bg-green-50 text-green-700 border-green-200', label: 'Routine', icon: Stethoscope };
    };

    const generateMockMetadata = (referral, index) => {
        let dateObj;
        let idVal;

        if (referral.createdAt) {
            dateObj = new Date(referral.createdAt);
            idVal = referral.id;
        } else {
            const now = new Date();
            dateObj = new Date(now.setDate(now.getDate() - index));
            idVal = `REF-2026-${(1042 + index).toString().padStart(4, '0')}`;
        }

        return {
            id: idVal,
            date: dateObj.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
            time: dateObj.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })
        };
    };

    const filteredReferrals = useMemo(() => {
        if (!searchTerm) return referrals;
        return referrals.filter(ref =>
            ref.hospital?.toLowerCase().includes(searchTerm.toLowerCase()) ||
            ref.assignedHospital?.toLowerCase().includes(searchTerm.toLowerCase())
        );
    }, [referrals, searchTerm]);

    return (
        <div className="max-w-6xl mx-auto space-y-6 pt-2 animate-in fade-in duration-500">
            {/* Header Section */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6 border-b border-surface-200/80 pb-6">
                <div>
                    <h1 className="text-3xl font-bold text-surface-900 font-display tracking-tight">Referral Registry</h1>
                    <p className="text-surface-500 mt-2 font-medium text-sm max-w-lg">Track and manage all patient assignments generated by your clinic. Select a case to view detailed clinical handover notes.</p>
                </div>
                <div className="w-full md:w-80 relative">
                    <Search className="w-5 h-5 absolute left-3 top-1/2 -translate-y-1/2 text-surface-400" />
                    <Input
                        placeholder="Search by facility name..."
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                        className="pl-10 bg-white border-surface-200 shadow-sm rounded-xl h-11"
                    />
                </div>
            </div>

            {/* Case List */}
            {isLoading ? (
                <div className="space-y-4 pt-4">
                    {[1, 2, 3, 4].map(i => (
                        <div key={i} className="h-24 bg-surface-100/50 rounded-2xl animate-pulse border border-surface-200/50" />
                    ))}
                </div>
            ) : filteredReferrals.length > 0 ? (
                <div className="space-y-4 pt-2">
                    {filteredReferrals.map((referral, index) => {
                        const meta = generateMockMetadata(referral, index);
                        const urgency = getUrgencySettings(referral.score);
                        const UrgencyIcon = urgency.icon;
                        const hospitalName = referral.hospital || referral.assignedHospital || 'Regional Medical Center';
                        const score = referral.score || Math.floor(Math.random() * 40) + 50;

                        return (
                            <div
                                key={index}
                                className="group bg-white border border-surface-200/80 rounded-2xl p-5 hover:border-brand-300 hover:shadow-clinical transition-all duration-200 flex flex-col md:flex-row relative overflow-hidden focus-within:ring-2 focus-within:ring-brand-500"
                            >
                                {/* Left Urgency Bar */}
                                <div className={`absolute left-0 top-0 bottom-0 w-1.5 ${urgency.color.split(' ')[0]}`}></div>

                                {/* Meta & ID */}
                                <div className="md:w-48 shrink-0 mb-4 md:mb-0 pl-2">
                                    <div className="flex items-center gap-2 mb-1">
                                        <FileText className="w-4 h-4 text-surface-400" />
                                        <span className="font-bold text-surface-900 font-display">{meta.id}</span>
                                    </div>
                                    <p className="text-sm text-surface-500 font-medium">{meta.date} • {meta.time}</p>
                                </div>

                                {/* Destination */}
                                <div className="flex-1 md:px-6 md:border-l md:border-surface-100 flex items-center mb-4 md:mb-0">
                                    <div className="w-10 h-10 rounded-xl bg-brand-50 text-brand-700 flex items-center justify-center shrink-0 mr-4 shadow-sm border border-brand-100/50">
                                        <Building2 className="w-5 h-5" />
                                    </div>
                                    <div>
                                        <p className="text-[11px] font-bold text-surface-400 uppercase tracking-widest mb-0.5">Assigned Destination</p>
                                        <h4 className="font-bold text-surface-900 text-lg leading-tight">{hospitalName}</h4>
                                    </div>
                                </div>

                                {/* Metrics & Status */}
                                <div className="flex items-center justify-between md:w-auto md:gap-8 bg-surface-50 md:bg-transparent -mx-5 px-5 py-4 md:p-0 md:mx-0 border-t border-surface-100 md:border-none">
                                    <div className="flex gap-6">
                                        <div className="text-center md:text-left">
                                            <p className="text-[11px] font-bold text-surface-400 uppercase tracking-widest mb-1.5">Priority</p>
                                            <div className={`inline-flex items-center justify-center w-9 h-9 rounded-full ${urgency.color} font-bold font-display border shadow-sm`}>
                                                {score}
                                            </div>
                                        </div>
                                        <div className="text-center md:text-left">
                                            <p className="text-[11px] font-bold text-surface-400 uppercase tracking-widest mb-1.5">Travel</p>
                                            <div className="flex items-center text-surface-700 font-semibold h-9">
                                                <Clock className="w-4 h-4 mr-1.5 text-surface-400" />
                                                {referral.travelTime || referral.estimatedTravelTime || '45m'}
                                            </div>
                                        </div>
                                    </div>

                                    <div className="flex flex-col items-end gap-2 ml-4">
                                        <Badge variant={
                                            referral.status === 'Escalated' ? 'danger' :
                                                referral.status === 'Closed Local - Treated' ? 'success' :
                                                    referral.status === 'Closed Local - Admitted' ? 'outline' :
                                                        referral.status === 'Pending' ? 'warning' : 'primary'
                                        } className="px-3">
                                            {referral.status || 'Pending'}
                                        </Badge>

                                        <button
                                            onClick={() => setSelectedReferral({ ...referral, meta, urgency, hospitalName, score })}
                                            className="text-xs font-bold text-brand-600 opacity-0 group-hover:opacity-100 transition-opacity flex items-center gap-1 hover:text-brand-800 cursor-pointer mt-1"
                                        >
                                            View file <ChevronRight className="w-3 h-3" />
                                        </button>
                                    </div>
                                </div>
                            </div>
                        );
                    })}
                </div>
            ) : (
                <div className="text-center py-20 bg-white border border-surface-200/80 rounded-2xl shadow-sm mt-4">
                    <div className="w-16 h-16 bg-surface-50 rounded-2xl flex items-center justify-center mx-auto mb-4 border border-surface-200">
                        <Search className="w-6 h-6 text-surface-400" />
                    </div>
                    <h3 className="text-lg font-bold text-surface-900 font-display mb-1">No cases found</h3>
                    <p className="text-surface-500 font-medium">Try adjusting your search terms or initiate a new transfer.</p>
                </div>
            )}

            {/* Referral Modal Overlay */}
            {selectedReferral && (
                <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-6 bg-surface-900/60 backdrop-blur-md animate-in fade-in duration-200">
                    {/* Ensure modal doesn't take 100% height to keep overlay visible */}
                    <div className="bg-white rounded-3xl shadow-clinical w-full max-w-2xl max-h-[85vh] flex flex-col overflow-hidden animate-in zoom-in-95 duration-200 ring-1 ring-surface-200/50">
                        {/* Modal Header */}
                        <div className="flex items-center justify-between px-6 py-4 border-b border-surface-100 bg-surface-50/50">
                            <div className="flex items-center gap-3">
                                <div className="w-10 h-10 rounded-xl bg-brand-50 text-brand-700 flex items-center justify-center border border-brand-100/50">
                                    <FileText className="w-5 h-5" />
                                </div>
                                <div>
                                    <h3 className="text-lg font-bold text-surface-900 font-display leading-tight">Case File</h3>
                                    <p className="text-xs font-bold text-surface-400 uppercase tracking-widest">{selectedReferral.meta.id}</p>
                                </div>
                            </div>
                            <button
                                onClick={() => setSelectedReferral(null)}
                                className="p-2 text-surface-400 hover:text-surface-600 hover:bg-surface-100 rounded-full transition-colors"
                            >
                                <X className="w-5 h-5" />
                            </button>
                        </div>

                        {/* Modal Content - Scrollable Region */}
                        <div className="p-6 md:p-8 space-y-8 overflow-y-auto custom-scrollbar flex-1">
                            {/* Top Section: Meta */}
                            <div className="flex flex-wrap gap-6 justify-between items-start">
                                <div>
                                    <p className="text-xs font-bold text-surface-400 uppercase tracking-widest mb-1">Generated</p>
                                    <p className="font-semibold text-surface-900">{selectedReferral.meta.date} at {selectedReferral.meta.time}</p>
                                </div>
                                <div className="text-right">
                                    <p className="text-xs font-bold text-surface-400 uppercase tracking-widest mb-1">Current Status</p>
                                    <Badge variant={
                                        selectedReferral.status === 'Escalated' ? 'danger' :
                                            selectedReferral.status === 'Closed Local - Treated' ? 'success' :
                                                selectedReferral.status === 'Closed Local - Admitted' ? 'outline' :
                                                    selectedReferral.status === 'Pending' ? 'warning' : 'primary'
                                    } className="px-3">
                                        {selectedReferral.status || 'Pending'}
                                    </Badge>
                                </div>
                            </div>

                            {/* Middle Section: Patient Information */}
                            {(selectedReferral.patientAge || selectedReferral.symptoms) && (
                                <div className="border-t border-surface-100 pt-6">
                                    <h4 className="text-sm font-bold text-surface-900 uppercase tracking-widest mb-4 flex items-center gap-2">
                                        <User className="w-4 h-4 text-brand-600" /> Patient Information
                                    </h4>
                                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                                        <div>
                                            <p className="text-xs font-bold text-surface-400 uppercase tracking-widest mb-1">Age</p>
                                            <p className="font-semibold text-surface-900">{selectedReferral.patientAge || 'N/A'}</p>
                                        </div>
                                        <div className="md:col-span-2">
                                            <p className="text-xs font-bold text-surface-400 uppercase tracking-widest mb-1">Chief Complaint / Symptoms</p>
                                            <p className="font-medium text-surface-700">{selectedReferral.symptoms || 'No symptoms recorded'}</p>
                                        </div>
                                    </div>

                                    {/* Vitals sub-section */}
                                    <div className="mt-4 bg-surface-50 rounded-xl p-4 border border-surface-100 relative overflow-hidden">
                                        <div className={`absolute top-0 left-0 bottom-0 w-1 ${selectedReferral.urgency?.color?.split(' ')[0] || 'bg-surface-200'}`}></div>
                                        <div className="flex justify-between items-start mb-3">
                                            <p className="text-xs font-bold text-surface-400 uppercase tracking-widest flex items-center gap-1.5 pl-2">
                                                <HeartPulse className="w-3.5 h-3.5 text-brand-600" /> Vitals
                                            </p>
                                            {selectedReferral.urgency?.label && (
                                                <Badge className={`${selectedReferral.urgency.color.split(' ')[0]} ${selectedReferral.urgency.color.split(' ')[1]} bg-opacity-20`}>
                                                    {selectedReferral.urgency.label}
                                                </Badge>
                                            )}
                                        </div>

                                        <div className="grid grid-cols-3 gap-4 pl-2">
                                            <div>
                                                <p className="text-[10px] font-bold text-surface-400 uppercase tracking-widest mb-1">BP</p>
                                                <p className="font-bold text-surface-900">{selectedReferral.bp || 'N/A'}</p>
                                            </div>
                                            <div>
                                                <p className="text-[10px] font-bold text-surface-400 uppercase tracking-widest mb-1">HR</p>
                                                <p className="font-bold text-surface-900">{selectedReferral.hr || 'N/A'}</p>
                                            </div>
                                            <div>
                                                <p className="text-[10px] font-bold text-surface-400 uppercase tracking-widest mb-1">SpO₂</p>
                                                <p className="font-bold text-surface-900">{selectedReferral.spo2 ? `${selectedReferral.spo2}%` : 'N/A'}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            )}

                            {/* Middle Section: AI Insight (if exists) */}
                            {selectedReferral.aiInsight && (
                                <div className="bg-brand-50/60 rounded-2xl p-5 border border-brand-100 flex items-start gap-4">
                                    <div className="p-2 bg-brand-100 text-brand-600 rounded-lg shrink-0 border border-brand-200 shadow-sm mt-0.5">
                                        <Sparkles className="w-5 h-5" />
                                    </div>
                                    <div>
                                        <p className="text-[11px] font-bold text-brand-600 uppercase tracking-widest mb-1">AI Clinical Assessment</p>
                                        <p className="text-sm font-medium text-surface-700 leading-relaxed">{selectedReferral.aiInsight}</p>
                                    </div>
                                </div>
                            )}

                            {/* Bottom Section: Destination & Metrics */}
                            <div className="bg-surface-50 rounded-2xl p-6 border border-surface-100 flex items-start gap-4">
                                <div className="p-3 bg-white text-brand-600 rounded-xl shadow-sm border border-surface-200 shrink-0">
                                    <Building2 className="w-6 h-6" />
                                </div>
                                <div>
                                    <p className="text-[11px] font-bold text-surface-400 uppercase tracking-widest mb-1 text-left">Assigned Destination</p>
                                    <h4 className="text-xl font-bold text-surface-900 font-display mb-1">{selectedReferral.hospitalName}</h4>
                                    <p className="text-sm font-medium text-brand-600 flex items-center gap-1.5">
                                        <MapPin className="w-4 h-4" /> Route Confirmed
                                    </p>
                                </div>
                            </div>

                            {/* Bottom Section: Metrics */}
                            <div className="grid grid-cols-2 gap-4">
                                <div className="border border-surface-100 rounded-2xl p-5 relative overflow-hidden">
                                    <div className={`absolute top-0 left-0 right-0 h-1.5 ${selectedReferral.urgency.color.split(' ')[0]}`}></div>
                                    <p className="text-[11px] font-bold text-surface-400 uppercase tracking-widest mb-2">Priority Score</p>
                                    <div className="flex items-baseline gap-2">
                                        <span className={`text-4xl font-black font-display tracking-tight ${selectedReferral.urgency.color.split(' ')[1]}`}>
                                            {selectedReferral.score}
                                        </span>
                                        <span className="text-sm font-bold text-surface-400">/ 100</span>
                                    </div>
                                    <p className={`text-sm font-bold mt-2 flex items-center gap-1.5 ${selectedReferral.urgency.color.split(' ')[1]}`}>
                                        <selectedReferral.urgency.icon className="w-4 h-4" /> {selectedReferral.urgency.label}
                                    </p>
                                </div>
                                <div className="border border-surface-100 rounded-2xl p-5">
                                    <p className="text-[11px] font-bold text-surface-400 uppercase tracking-widest mb-2">Estimated Travel</p>
                                    <div className="flex items-baseline gap-2">
                                        <span className="text-4xl font-black font-display tracking-tight text-surface-900">
                                            {selectedReferral.travelTime || selectedReferral.estimatedTravelTime || '45'}
                                        </span>
                                        <span className="text-sm font-bold text-surface-400">mins</span>
                                    </div>
                                    <p className="text-sm font-medium text-surface-500 mt-2 flex items-center gap-1.5">
                                        <Clock className="w-4 h-4" /> Transit time
                                    </p>
                                </div>
                            </div>
                        </div>

                        {/* Modal Footer */}
                        <div className="px-6 py-4 border-t border-surface-100 bg-surface-50 flex justify-between items-center shrink-0">
                            <button
                                onClick={() => window.print()}
                                className="text-sm font-bold text-surface-600 hover:text-brand-600 flex items-center gap-2 transition-colors"
                            >
                                <Printer className="w-4 h-4" /> Print Referral
                            </button>
                            <button
                                onClick={() => setSelectedReferral(null)}
                                className="px-6 py-2.5 bg-surface-900 hover:bg-brand-600 text-white font-semibold rounded-xl transition-all shadow-sm flex items-center gap-2"
                            >
                                <X className="w-4 h-4" /> Close / Back to Registry
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default ReferralStatus;
