import React, { useState, useEffect, useMemo } from 'react';
import { getReferrals } from '../api/referrals';
import { Badge } from '../components/ui/Badge';
import { Input } from '../components/ui/Input';
import { Search, MapPin, Clock, Building2, ChevronRight, Stethoscope, AlertCircle, FileText } from 'lucide-react';

const ReferralStatus = () => {
    const [referrals, setReferrals] = useState([]);
    const [isLoading, setIsLoading] = useState(true);
    const [searchTerm, setSearchTerm] = useState('');

    useEffect(() => {
        const fetchReferrals = async () => {
            try {
                const data = await getReferrals();
                setReferrals(data);
            } catch (error) {
                console.error("Failed to load referrals", error);
            } finally {
                setIsLoading(false);
            }
        };

        fetchReferrals();
    }, []);

    // Helper functions for mock data enhancement
    const getUrgencySettings = (scoreStr) => {
        const score = parseInt(scoreStr, 10);
        if (isNaN(score)) return { color: 'bg-surface-100 text-surface-700 border-surface-200', label: 'Unknown', icon: AlertCircle };
        if (score >= 80) return { color: 'bg-red-50 text-red-700 border-red-200', label: 'Critical', icon: AlertCircle };
        if (score >= 60) return { color: 'bg-amber-50 text-amber-700 border-amber-200', label: 'Urgent', icon: Clock };
        return { color: 'bg-green-50 text-green-700 border-green-200', label: 'Routine', icon: Stethoscope };
    };

    const generateMockMetadata = (index) => {
        const now = new Date();
        const date = new Date(now.setDate(now.getDate() - index));
        return {
            id: `REF-2026-${(1042 + index).toString().padStart(4, '0')}`,
            date: date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
            time: date.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })
        };
    };

    const filteredReferrals = useMemo(() => {
        if (!searchTerm) return referrals;
        return referrals.filter(ref =>
            ref.hospital?.toLowerCase().includes(searchTerm.toLowerCase()) ||
            ref.assignedHospital?.toLowerCase().includes(searchTerm.toLowerCase())
        );
    }, [referrals, searchTerm]);

    return (
        <div className="max-w-6xl mx-auto space-y-6 pt-2 animate-in fade-in duration-500">
            {/* Header Section */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6 border-b border-surface-200/80 pb-6">
                <div>
                    <h1 className="text-3xl font-bold text-surface-900 font-display tracking-tight">Referral Registry</h1>
                    <p className="text-surface-500 mt-2 font-medium text-sm max-w-lg">Track and manage all patient assignments generated by your clinic. Select a case to view detailed clinical handover notes.</p>
                </div>
                <div className="w-full md:w-80 relative">
                    <Search className="w-5 h-5 absolute left-3 top-1/2 -translate-y-1/2 text-surface-400" />
                    <Input
                        placeholder="Search by facility name..."
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                        className="pl-10 bg-white border-surface-200 shadow-sm rounded-xl h-11"
                    />
                </div>
            </div>

            {/* Case List */}
            {isLoading ? (
                <div className="space-y-4 pt-4">
                    {[1, 2, 3, 4].map(i => (
                        <div key={i} className="h-24 bg-surface-100/50 rounded-2xl animate-pulse border border-surface-200/50" />
                    ))}
                </div>
            ) : filteredReferrals.length > 0 ? (
                <div className="space-y-4 pt-2">
                    {filteredReferrals.map((referral, index) => {
                        const meta = generateMockMetadata(index);
                        const urgency = getUrgencySettings(referral.score);
                        const UrgencyIcon = urgency.icon;
                        const hospitalName = referral.hospital || referral.assignedHospital || 'Regional Medical Center';
                        const score = referral.score || Math.floor(Math.random() * 40) + 50;

                        return (
                            <div
                                key={index}
                                className="group bg-white border border-surface-200/80 rounded-2xl p-5 hover:border-brand-300 hover:shadow-clinical transition-all duration-200 flex flex-col md:flex-row relative overflow-hidden focus-within:ring-2 focus-within:ring-brand-500"
                            >
                                {/* Left Urgency Bar */}
                                <div className={`absolute left-0 top-0 bottom-0 w-1.5 ${urgency.color.split(' ')[0]}`}></div>

                                {/* Meta & ID */}
                                <div className="md:w-48 shrink-0 mb-4 md:mb-0 pl-2">
                                    <div className="flex items-center gap-2 mb-1">
                                        <FileText className="w-4 h-4 text-surface-400" />
                                        <span className="font-bold text-surface-900 font-display">{meta.id}</span>
                                    </div>
                                    <p className="text-sm text-surface-500 font-medium">{meta.date} • {meta.time}</p>
                                </div>

                                {/* Destination */}
                                <div className="flex-1 md:px-6 md:border-l md:border-surface-100 flex items-center mb-4 md:mb-0">
                                    <div className="w-10 h-10 rounded-xl bg-brand-50 text-brand-700 flex items-center justify-center shrink-0 mr-4 shadow-sm border border-brand-100/50">
                                        <Building2 className="w-5 h-5" />
                                    </div>
                                    <div>
                                        <p className="text-[11px] font-bold text-surface-400 uppercase tracking-widest mb-0.5">Assigned Destination</p>
                                        <h4 className="font-bold text-surface-900 text-lg leading-tight">{hospitalName}</h4>
                                    </div>
                                </div>

                                {/* Metrics & Status */}
                                <div className="flex items-center justify-between md:w-auto md:gap-8 bg-surface-50 md:bg-transparent -mx-5 px-5 py-4 md:p-0 md:mx-0 border-t border-surface-100 md:border-none">
                                    <div className="flex gap-6">
                                        <div className="text-center md:text-left">
                                            <p className="text-[11px] font-bold text-surface-400 uppercase tracking-widest mb-1.5">Priority</p>
                                            <div className={`inline-flex items-center justify-center w-9 h-9 rounded-full ${urgency.color} font-bold font-display border shadow-sm`}>
                                                {score}
                                            </div>
                                        </div>
                                        <div className="text-center md:text-left">
                                            <p className="text-[11px] font-bold text-surface-400 uppercase tracking-widest mb-1.5">Travel</p>
                                            <div className="flex items-center text-surface-700 font-semibold h-9">
                                                <Clock className="w-4 h-4 mr-1.5 text-surface-400" />
                                                {referral.travelTime || referral.estimatedTravelTime || '45m'}
                                            </div>
                                        </div>
                                    </div>

                                    <div className="flex flex-col items-end gap-2 ml-4">
                                        <Badge variant={referral.status === 'Accepted' ? 'success' : 'warning'} className="px-3">
                                            {referral.status || 'Pending'}
                                        </Badge>
                                        <button className="text-xs font-bold text-brand-600 opacity-0 group-hover:opacity-100 transition-opacity flex items-center gap-1 hover:text-brand-800">
                                            View file <ChevronRight className="w-3 h-3" />
                                        </button>
                                    </div>
                                </div>
                            </div>
                        );
                    })}
                </div>
            ) : (
                <div className="text-center py-20 bg-white border border-surface-200/80 rounded-2xl shadow-sm mt-4">
                    <div className="w-16 h-16 bg-surface-50 rounded-2xl flex items-center justify-center mx-auto mb-4 border border-surface-200">
                        <Search className="w-6 h-6 text-surface-400" />
                    </div>
                    <h3 className="text-lg font-bold text-surface-900 font-display mb-1">No cases found</h3>
                    <p className="text-surface-500 font-medium">Try adjusting your search terms or initiate a new transfer.</p>
                </div>
            )}
        </div>
    );
};

export default ReferralStatus;
